# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pUxOW-gDK5aTNP5s77eFUWb8X8Z8hyVH

Task 1.1
"""

jumbled_superheroes = ['DocToR_sTRAnge', 'sPidERmaN','MoON_KnigHT','caPTAIN_aMERIca','hULK' ]

indices = []
decoded_names = []

for index, name in enumerate(jumbled_superheroes):
    indices.append(index)
    decoded_names.append(name.lower().replace('_', ' '))

name_lengths = list(map(lambda x: len(x), decoded_names))

indices.sort(key=lambda x: name_lengths[x])

print("Phase 5 kickoff list:")
for index in indices:
    print(decoded_names[index].title())

"""Task 1.2"""

lst = ['0001','0011','0101','1011','1101','1111']

new_lst = [int(binary,2) for binary in lst]
print("new_lst = ",new_lst)
print(len(new_lst))

while len(new_lst)>2:
  x1=new_lst.pop(0)
  print(x1)
  x2=new_lst.pop(0)
  print(x2)
  sum = x1+x2
  new_lst.append(sum)
print("new_lst =",new_lst)

"""Task 1.3"""





